image:
  - bmp
  - gif
  - jpeg
  - jpg
  - png
  - svg
  - tga
video:
  - flv
  - mp4
  - ogv
  - webm
audio:
  - m4a
  - mp3
  - ogg
  - wav
archive:
  - 7z
  - arj
  - bz2
  - bzip2
  - cab
  - cpio
  - dds # Treat as binary to allow downloading
  - deb
  - dmg
  - exe
  - fat
  - flac # Treat as binary to allow downloading
  - gz
  - gzip
  - hfs
  - iso
  - lha
  - lzh
  - lzma
  - ntfs
  - pdf
  - rar
  - raw # Treat as binary to allow downloading
  - rpm
  - squashfs
  - swm
  - tar
  - taz
  - tbz
  - tbz2
  - tgz
  - torrent # Treat as binary to allow downloading
  - tpz
  - txz
  - vhd
  - wim
  - xar
  - xz
  - z
  - zip
paste:
  - bash
  - bashrc
  - bat
  - batch
  - c
  - cmd
  - conf
  - cpp
  - css
  - h
  - hpp
  - htaccess
  - htm
  - html
  - in
  - java
  - js
  - md5 # hash dump
  - php
  - pl
  - py
  - rb
  - rc
  - sh
  - txt
  - xml
  - yaml
  - yml
  - zsh
  - zshrc
